export default function AP2SmokePage() {
  return (
    <main style={{ padding: 40 }}>
      <h1>AP2 Smoke Test</h1>
      <p id="ap2-proof">
        AP2 verification line – generated by automation
      </p>
    </main>
  );
}
